### ISSUE TITLE
Old version in Debian, new upstream homepage

### ISSUE THREAD

**Issue by ssvb** [375gnu/hunspell-be#2]
The upstream has apparently moved from sourceforge to github: https://github.com/mikalai-udodau/spell-be

I also see that only version 0.53-3.1 is currently packaged in Debian. Are there any plans to eventually update it to a more recent version?

**Comment by 375gnu** [comment]
There were no plans but I'll try to update.

**Comment by 375gnu** [comment]
https://packages.debian.org/search?suite=all&searchon=names&keywords=hunspell-be
